### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jku** [sigstore/sigstore-conformance#103]
I'd like to improve the publishing pipeline for extremely-dangerous-public-oidc-beacon (by making the token available in GH Pages so it's easier to download, see [PR](https://github.com/sigstore-conformance/extremely-dangerous-public-oidc-beacon/pull/7)), but doing so requires sigstore-conformance users to be running current main branch contents, specifically  PR 102.

First step would be a new sigstore-conformance release. Release right now would contain:
* #102
* #100 (#99)
* #98 (#97)
* #95 (#87, #94)

There's no rush or deadline from my POV: I'm filing this so I don't lose track.

**Comment by woodruffw** [comment]
Makes sense to me. I can cut a release here now (or at least prepare one for cutting).

**Comment by woodruffw** [comment]
Released with 0.0.7, thanks @jku!

**Comment by jku** [comment]
Thank you. I'll followup next week to check that users have upgraded and then make a PR for the token publishing
