### ISSUE TITLE
Test against staging too

### ISSUE THREAD

**Issue by jku** [sigstore/sigstore-conformance#121]
It eould be useful if this project also ensured that the client works with current staging infra:
* client developers would find out ASAP if their client breaks when something changes in staging: these changes are likely to propagate to production later
  * in case of infrastructure bug, client developer complaints could prevent the propagation of this bug
  * in case of client bug or missing feature this gives client developer more time to fix issues (or ask for delay in infrastructure change propagation)
  
There might be several ways to accomplish this but a simple one might be to  
* Add a `--staging` flag to the client-under-test CLI spec
* add a single new test `test_simple_staging()` that does exactly what `test_simple()` does but against staging

cc @loosebazooka

**Comment by woodruffw** [comment]
Adding `--staging` works for me, but thinking even more generally: it'd be nice to make this parametric, i.e. allow *every* test to run on both staging and production (if supported by the client).

(But that's a more generic, long-term thought. I'm okay with having this be one-off for now.)

**Comment by loosebazooka** [comment]
I can add a staging flag into the java "cli".

I also think it might make sense to run this on a cron (if people aren't already). Currently java only runs it on PRs.

**Comment by woodruffw** [comment]
> I also think it might make sense to run this on a cron (if people aren't already). Currently java only runs it on PRs.

Agreed -- I believe we run it on a schedule on `sigstore-python`, and it's helped us with regressions/availability issues before!

**Comment by jku** [comment]
> This plan assumes the workflows running the suite will add a new step (essentially will run the action a second time for staging).

I suppose alternatively action.py could call pytest twice if `--staging` is given to it, once with staging and once with prod.

**Comment by steiza** [comment]
> currently all tests supposedly run against staging: this does not actually work as all of the embedded assets are for production infra

I believe sigstore-go, sigstore-java, sigstore-js, and sigstore-python all now support providing a custom trust root, so an alternative here would be to ensure the tests with embedded assets include a trust root for production, if they don't currently have one.

**Comment by woodruffw** [comment]
> I suppose alternatively action.py could call pytest twice if `--staging` is given to it, once with staging and once with prod.

I slightly prefer this, as a matter of keeping changes/configuration effort on each downstream's CI to a minimum. Otherwise your proposal SGTM @jku!

> I believe sigstore-go, sigstore-java, sigstore-js, and sigstore-python all now support providing a custom trust root, so an alternative here would be to ensure the tests with embedded assets include a trust root for production, if they don't currently have one.

We aren't _quite_ there yet on the sigstore-python side yet, unfortunately: https://github.com/sigstore/sigstore-python/issues/821

(Taking a step back: I suppose we need to define how `--staging` and `--trusted-root` will interact in the conformance suite. We could say that they're mutually exclusive, I think?)

**Comment by jku** [comment]
Supporting `trusted-root` seems like a good plan but since  AFAIK that is not possible for a signing client at the moment, I think that's a future feature.

Current plan is for `enable-staging` to be an "additional feature" (in other words `enable-staging=true` does not disable testing production). With `trusted-root` that's probably different: I would expect staging and production to not be tested in that case, just the infrastructure defined by the trustedroot.
