### ISSUE TITLE
Allow testing bundle verification without requiring a client to implement signing

### ISSUE THREAD

**Issue by steiza** [sigstore/sigstore-conformance#81]
**Description**

Today, https://github.com/sigstore/sigstore-conformance/blob/main/test/test_bundle.py requires a client to implement signing in order to test bundle verification. It would be nice to be able to test verification without requiring the client to implement signing.

**Comment by steiza** [comment]
Now that https://github.com/sigstore/sigstore-conformance/pull/82 has landed, I think this is done!

**Comment by woodruffw** [comment]
Awesome! Would it help to have a new version tagged for #82?

**Comment by steiza** [comment]
> Would it help to have a new version tagged

If it's easy, sure! Eventually we'll want a version tagged for https://github.com/sigstore/sigstore-go, but we're a few other steps / weeks around that being the case.

**Comment by woodruffw** [comment]
> If it's easy, sure! Eventually we'll want a version tagged for https://github.com/sigstore/sigstore-go, but we're a few other steps / weeks until that's the case.

Yep, it's just a `git tag`. Doing now!
