### ISSUE TITLE
Make it easier to run verification tests locally

### ISSUE THREAD

**Issue by steiza** [sigstore/sigstore-conformance#99]
**Description**

The existing instructions to run the tests locally involve using a GitHub token to get an OIDC JWT from https://github.com/sigstore-conformance/extremely-dangerous-public-oidc-beacon.

If you're only testing verification use-cases though, you don't need an OIDC JWT.

We should make it so if you run `pytest test --skip-signing ...` you don't need a GitHub token, since you don't need an OIDC JWT.

**Comment by woodruffw** [comment]
Fully I agreed! I saw you opened #100; thank you!
